name: DMP 2024 Design Project Template
description: List a new design project for Dedicated Mentoring Program 2024
title: "[DMP 2024]: "
labels: ["DMP 2024" , "Product Usability"]
body:
  - type: textarea
    id: ticket-description
    validations:
      required: true
    attributes:
      label: Description
      description: Provide a brief description of the problem statement here. Include any relevant context or background information (user research findings, list of user personas / target users affected, etc.,.)
  
  - type: textarea
    id: key-design-research-questions
    validations:
      required: true
    attributes:
      label: Key design-research questions
      description: Identify key design problems / research questions to be addressed during the project phase

  - type: textarea
    id: current-state
    validations:
      required: true
    attributes:
      label: Current State
      description: Describe the current state of the problem. What are the gaps / unanswered questions wrt problem statements identified? What is the user experience like currently? 

  - type: textarea
    id: desired-state
    validations:
      required: true
    attributes:
      label: Desired State 
      description: What is the roadmap for the intended users and the respective product? Please list if there are any product / feature specific expected goals. (These could be overall and not limited to the DMP project goals)

  - type: textarea
    id: ticket-goals
    validations:
      required: true
    attributes:
      label: Goals & Mid-Point Milestone
      description: List the goals of the project (What is the expected end outcome from the project). Add the tasks that must be completed by Mid-point check-in i.e 1.5 months into the execution period 
      value: |
        ## Goals
        - [ ] [Goal 1]
        - [ ] [Goal 2]
        - [ ] [Goal 3]
        - [ ] [Goal 4]
        - [ ] [Goals Achieved By Mid-point Milestone]

  - type: textarea
    id: ticket-acceptance-criteria
    validations:
      required: true
    attributes:
      label: Acceptance Criteria
      description: Define specific criteria that must be met for this problem statement to be considered resolved. These criteria should be measurable and observable, allowing for clear validation of the solution.

  - type: textarea
    id: ticket-mockups
    attributes:
      label: Existing Mockups/Wireframes
      description: Include links to any visual aids, mockups, wireframes, or diagrams that help illustrate what the final product should look like. This is not always necessary, but can be very helpful in many cases.

  - type: input
    id: ticket-product
    attributes:
      label: Product Name
      placeholder: Enter Product Name
    validations:
      required: true

  - type: dropdown
    id: ticket-organisation
    attributes:
      label: Organisation Name
      description: Enter Organisation Name
      multiple: false
      options:
        - Bandhu
        - Blockster Global (CREDBEL)
        - Civis
        - Dhwani
        - Dhiway
        - EGov
        - EkShop Marketplace
        - FIDE
        - If Me
        - Key Education Foundation
        - Norwegian Meteorological Institute
        - Planet Read
        - Project Second Chance
        - Reap Benefit
        - SamagraX
        - ShikshaLokam
        - Tech4Dev
        - Tekdi
        - The Mifos Initiative
        - Tibil
        - Ushahidi
        - Arghyam
        - Piramal Swasthya Management Research Institute
        - Dimagi 
        - Win Over Cancer 
        - Protean 
        - Thoughtworks 
    validations:
      required: true

  - type: dropdown
    id: ticket-governance-domain
    attributes:
      label: Domain
      options:
        - ⁠Healthcare 
        - ⁠Education
        - Financial Inclusion
        - ⁠Livelihoods
        - ⁠Skilling 
        - ⁠Learning & Development
        - ⁠Agriculture
        - ⁠Service Delivery
        - Open Source Library
        - Water
    validations:
      required: true

  - type: textarea
    id: ticket-mentors
    attributes:
      label: Mentor(s)
      description: Please tag relevant mentors for the ticket
    validations:
      required: true
  
